apiVersion: v1
kind: Service
metadata:
  name: openstatus-libsql
  labels:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: libsql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: libsql
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 5001
      targetPort: 5001
