apiVersion: v1
kind: Secret
metadata:
  name: openstatus-env
type: Opaque
stringData:
  # Core
  NODE_ENV: "development"
  NEXT_PUBLIC_URL: "doritinho.massaini.xyz"
  AUTH_SECRET: "Gqb8c/KXzaeRkNKEfabd71WWiofRRGml+JegkwVN9JY="
  SELF_HOST: "true"

  # Database
  DATABASE_URL: "http://openstatus-libsql:8080"
  DATABASE_AUTH_TOKEN: "test"

  # Email
  RESEND_API_KEY: "test"

  # Analytics
  TINY_BIRD_API_KEY: ""
  TINYBIRD_URL: "http://openstatus-tinybird:7181"

  # Redis / Queue (optional)
  UPSTASH_REDIS_REST_URL: ""
  UPSTASH_REDIS_REST_TOKEN: ""
  QSTASH_CURRENT_SIGNING_KEY: ""
  QSTASH_NEXT_SIGNING_KEY: ""
  QSTASH_TOKEN: ""
  QSTASH_URL: "https://qstash.upstash.io/v1/publish/"

  # Auth providers (optional)
  AUTH_GITHUB_ID: ""
  AUTH_GITHUB_SECRET: ""
  AUTH_GOOGLE_ID: ""
  AUTH_GOOGLE_SECRET: ""

  # Cloud / cron (optional)
  GCP_PROJECT_ID: ""
  GCP_LOCATION: ""
  GCP_CLIENT_EMAIL: ""
  GCP_PRIVATE_KEY: ""
  CRON_SECRET: ""

  # API keys (optional)
  UNKEY_API_ID: ""
  UNKEY_TOKEN: ""
  SUPER_ADMIN_TOKEN: ""
  FLY_REGION: "self-hosted"

  # Misc
  SCREENSHOT_SERVICE_URL: ""
  OPENSTATUS_INGEST_URL: "http://openstatus-private-location:8080"
  OPENSTATUS_KEY: ""
