apiVersion: v1
kind: Service
metadata:
  name: openstatus-private-location
  labels:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: private-location
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: private-location
  ports:
    - name: http
      port: 8080
      targetPort: 8080
