apiVersion: v1
kind: Service
metadata:
  name: openstatus-server
  labels:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
