apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstatus-status-page
  labels:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: status-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openstatus
      app.kubernetes.io/component: status-page
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openstatus
        app.kubernetes.io/component: status-page
    spec:
      containers:
        - name: status-page
          image: brunomassaini/openstatus-status-page:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - secretRef:
                name: openstatus-env
          env:
            - name: DATABASE_URL
              value: http://openstatus-libsql:8080
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: AUTH_TRUST_HOST
              value: "true"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
