apiVersion: v1
kind: Service
metadata:
  name: openstatus-status-page
  labels:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: status-page
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: status-page
  ports:
    - name: http
      port: 3000
      targetPort: 3000
