apiVersion: v1
kind: Service
metadata:
  name: openstatus-workflows
  labels:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: workflows
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openstatus
    app.kubernetes.io/component: workflows
  ports:
    - name: http
      port: 3000
      targetPort: 3000
